### ISSUE TITLE
Docker image not working out of the box

### ISSUE THREAD

**Issue by tasugo** [asturiashacking/asturiashacking.github.io#4]
### Expected behaviour
`docker-compose up` ends up with the docker container running in the background and the website can be reach at `http://localhost:1313`

### Actual behaviour
```
docker-compose up
Starting asturiashackinggithubio_web_1 ... 
Starting asturiashackinggithubio_web_1 ... done
Attaching to asturiashackinggithubio_web_1
web_1  | [18:23:01] Local gulp not found in /asturiashacking
web_1  | [18:23:01] Try running: npm install gulp
asturiashackinggithubio_web_1 exited with code 1
```

### Steps to reproduce
Clone the repo and `docker-compose up`

**Comment by tasugo** [comment]
I'm working on a fix right now. @sergioalvz I can't add tags to the issue, am I not and admin of this repo? 😛

**Comment by sergioalvz** [comment]
That's right! I've just added you to the @asturiashacking/admin team now :)

**Comment by sergioalvz** [comment]
Any updates about this issue? Strangely enough, I'm not able to reproduce it (I've destroyed all the related containers and `docker-compose up` re-builds everything again without any problems...).

I'm using Docker for Mac.

```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87

$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

**Comment by tasugo** [comment]
I counldn't further investigate the issue, but I can assure you that it is still present as of yesterday, with a fresh installation of Ubuntu and the first `docker-compose up`. I'll try to get to the guts tonight and see if I can come up with a solution.

**Comment by rubfi** [comment]
I had the same issue.

```
Debian sid
$ docker --version
Docker version 1.13.1, build 092cba3
$ docker-compose --version
docker-compose version 1.8.0, build unknown
```
The problem was related to the local gulp missing in /asturiashacking

`RUN npm install` was installing the dependencies in /asturiashacking/node_modules directory, but /asturiashacking was overriden by the volume defined in docker-compose.yml, so node_modules directory was missing when launching `gulp server`

This issue could be solved linking locally required modules.  It can be done using `npm link` in the docker-compose.yml (see #5)

e.g: `npm link gulp gulp-postcss postcss-import postcss-cssnext cssnano`
